# Data Structures

One of the keys to understanding pandas is to understand the data model. At the core of pandas are two data structures. The most widely used data structures are the Series and the DataFrame for dealing with array data and tabular data. This table shows their analogs in the spreadsheet and database world.


| Data Structure| Dimensionality| Spreadsheet Analog| Databse Analog|
|-|-|-|-|
|Series|1D|Column|Column|
|DataFrame|2D|Single Sheet|Table|

DataFrame is similar to a sheet with rows and columns, while a Series is similar to a single column 
of data (when we refer to a column of data in this text, we are referring to a Series).

## Numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

"Series," "DataFrame," "Databases," and "Excel" are all data-related concepts or tools used in the context of managing and analyzing data.

 Series and DataFrames are data structures used in data analysis with Pandas in Python, while databases are used for structured data storage and retrieval, and Excel is a spreadsheet tool often used for simpler data analysis and reporting.

# Data Structures

One of the keys to understanding pandas is to understand the data model. At the core of pandas are two data structures. The most widely used data structures are the Series and the DataFrame for dealing with array data and tabular data. This table shows their analogs in the spreadsheet and database world.


| Data Structure| Dimensionality| Spreadsheet Analog| Databse Analog|
|-|-|-|-|
|Series|1D|Column|Column|
|DataFrame|2D|Single Sheet|Table|

DataFrame is similar to a sheet with rows and columns, while a Series is similar to a single column 
of data (when we refer to a column of data in this text, we are referring to a Series).

## Pandas

In pandas, the two-dimensional counterpart to the one-dimensional Series is the DataFrame. If we want to understand this data structure, it helps to know how it is constructed. This chapter will
introduce the dataframe.


Dataframes can be created from many types of input:
- columns (dicts of lists)
- rows (list of dicts)
- CSV, xlsx files (pd.read_csv)
- NumPy ndarrays
- other: SQL, HDF5, arrow, etc

> Just like an excel table is made up of columns, a DataFrame is made up of Series Data Types

# Pandas Series

there are two main types of operations you can perform on Series and DataFrame objects.
these are operator methods and attributes.

## Operator Methods

A Series is used to model one-dimensional data. The Series object also has a few more bits of data,
including an index and a name. A common idea through pandas is the notion of an axis. Because
a series is one-dimensional, it has a single axis—the index.
Below is a table of counts of deposits amounts by customers.


||Data|
|-|-|
|0|145|
|1|142|
|2|38|
|3|13| We

### Numerical Operations

|Method|Operator|Description|
|-|-|-|
|s.add(s2) | s + s2 | Adds series
|s.radd(s2) | s2 + s | Adds series
|s.sub(s2) | s - s2 | Subtracts series
|s.rsub(s2) | s2 - s | Subtracts series
|s.mul(s2) s.multiply(s2) | s * s2 | Multiplies series
|s.rmul(s2) | s2 * s | Multiplies series
|s.div(s2) s.truediv(s2) | s / s2 | Divides series
|s.mod(s2) | s % s2 | Modulo of series division
|s.eq(s2) | s2 == s | Elementwise equals of series
|s.ne(s2) | s2 != s | Elementwise not equals of series
|s.gt(s2) | s > 2 | Elementwise greater than of series
|s.ge(s2) | s >= 2 | Elementwise greater than or equals of series
|s.lt(s2) | s < 2 | Elementwise less than of series
|s.le(s2) | s <= 2  | Elementwise less than or equals of series

|Method|Description|
|-|-|
|'mad' |Return the mean absolute deviation.|
|'max' |Return the maximum value.|
|'mean'| Return the mean value.|
|'median'| Return the median value.|
|'min' |Return the minimum value.|
|'nbytes' |Return the number of bytes of the data.|
|'ndim' |Return the number of dimensions (1) of the data.|
|'nunique' |Return the count of unique values.|
|'quantile' |Return the median value. Can override q to specify other quantile.|
|'sem' |Return the unbiased standard error.|
|'size' |Return the size of the data.|
|'skew' |Return the unbiased skew of the data. Negativeindicates tail is on the left side.|
|'std' |Return the standard deviation of the data.|
|'sum' |Return the sum of the series.|

In [1]:
import pandas as pd

data = pd.read_csv("transaction_data.csv")
data = pd.DataFrame(data)
data

     Item_Description  Amount Traffic_Source Session_Duration
0            Notebook    20.0         Direct            3,470
1       Google Hoodie   124.0         Direct              401
2      Greeting Cards     6.0    Paid Search            2,608
3                 NaN     NaN            NaN            2,130
4             Lanyard     6.0         Direct            3,517
...               ...     ...            ...              ...
7391  Android T-Shirt    20.0       Referral            2,223
7392  Google Stickers     5.0    Paid Search            3,101
7393    Google Hoodie   124.0         Direct            2,107
7394    Google Hoodie   124.0   Social Media              919
7395    Google Hoodie   124.0    Paid Search               11

[7396 rows x 4 columns]

In [5]:
data.head(10)

      Item_Description  Amount Traffic_Source Session_Duration
0             Notebook    20.0         Direct            3,470
1        Google Hoodie   124.0         Direct              401
2       Greeting Cards     6.0    Paid Search            2,608
3                  NaN     NaN            NaN            2,130
4              Lanyard     6.0         Direct            3,517
5      Google Stickers     5.0    Paid Search              706
6        Google Hoodie   124.0       Referral            3,443
7      Google Stickers     5.0    Paid Search            1,728
8      Google Stickers     5.0   Social Media            1,227
9  Google Water Bottle    10.0   Social Media            1,198

In [7]:
data.tail(10)

     Item_Description  Amount  Traffic_Source Session_Duration
7386  Google Stickers     5.0  Organic Search            1,978
7387  Google Stickers     5.0          Direct              106
7388         Notebook    20.0    Social Media            1,308
7389  Google Stickers     5.0          Direct            3,008
7390  Google Stickers     5.0          Direct            1,502
7391  Android T-Shirt    20.0        Referral            2,223
7392  Google Stickers     5.0     Paid Search            3,101
7393    Google Hoodie   124.0          Direct            2,107
7394    Google Hoodie   124.0    Social Media              919
7395    Google Hoodie   124.0     Paid Search               11

In [9]:
type(data)

pandas.core.frame.DataFrame

In [11]:
type(data["Amount"])

pandas.core.series.Series

In [15]:
data[["Amount"]]

      Amount
0       20.0
1      124.0
2        6.0
3        NaN
4        6.0
...      ...
7391    20.0
7392     5.0
7393   124.0
7394   124.0
7395   124.0

[7396 rows x 1 columns]

In [21]:
amount = data["Amount"]

amount[3]

nan

In [23]:
amount > 50

0       False
1        True
2       False
3       False
4       False
        ...
7391    False
7392    False
7393     True
7394     True
7395     True
Name: Amount, Length: 7396, dtype: bool

In [26]:
amount[amount > 50]

1       124.0
6       124.0
11      124.0
17      124.0
18      124.0
        ...
7378    115.0
7379    124.0
7393    124.0
7394    124.0
7395    124.0
Name: Amount, Length: 1707, dtype: float64

In [30]:
mask = amount > amount.median()
mask

0        True
1        True
2       False
3       False
4       False
        ...
7391     True
7392    False
7393     True
7394     True
7395     True
Name: Amount, Length: 7396, dtype: bool

In [32]:
amount[mask]

0        20.0
1       124.0
6       124.0
11      124.0
15       18.0
        ...
7388     20.0
7391     20.0
7393    124.0
7394    124.0
7395    124.0
Name: Amount, Length: 3438, dtype: float64

In [34]:
second_amount = amount.copy()+5
second_amount

0        25.0
1       129.0
2        11.0
3         NaN
4        11.0
        ...
7391     25.0
7392     10.0
7393    129.0
7394    129.0
7395    129.0
Name: Amount, Length: 7396, dtype: float64

In [36]:
amount + second_amount

0        45.0
1       253.0
2        17.0
3         NaN
4        17.0
        ...
7391     45.0
7392     15.0
7393    253.0
7394    253.0
7395    253.0
Name: Amount, Length: 7396, dtype: float64

In [38]:
amount.add(second_amount, fill_value =0)

0        45.0
1       253.0
2        17.0
3         NaN
4        17.0
        ...
7391     45.0
7392     15.0
7393    253.0
7394    253.0
7395    253.0
Name: Amount, Length: 7396, dtype: float64

With the series defined below:

```{python}
ser = df['Amount']
```
Find the following:
1. Find the count of non-missing values of a series.
2. Find the number of entries of a series.
3. Find the number of unique entries of a series.
4. Find the mean value of a series.
5. Find the maximum value of a serf the

### Series Attributes

attributes allow you to inspect and retrieve information about the structure and characteristics of a Pandas Series, which is useful for data analysis and manipulation. You can access these attributes by appending them to a Series object

commonly used Pandas Series attributes:

1. `index`: Returns the index (row labels) of the Series.
2. `values`: Returns the data values of the Series as a NumPy array.
3. `name`: Returns or sets the name of the Series.
4. `dtype`: Returns the data type of the elements in the Series.
5. `size`: Returns the number of elements in the Series.
6. `shape`: Returns a tuple representing the shape of the Series (always `(n,)` for a Series).
7. `empty`: Returns True if the Series is empty.
8. `is_unique`: Returns True if all elements are unique.
9. `nunique()`: Returns the number of unique elements.
10. `count()`: Returns the number of non-null (non-missing) elements.
11. `head(n)`: Returns the first n elements of the Series.
12. `tail(n)`: Returns the last n elements of the Series.
13. `describe()`: Generates summary statistics for the Series.
14. `unique()`: Returns an array of unique elements.
15. `min()`: Returns the minimum value in the Series.
16. `max()`: Returns the maximum value in the Series.
17. `mean()`: Returns the mean (average) value of the Series.
18. `median()`: Returns the median value of the Series.
19. `std()`: Returns the standard deviation of the Series.
20. `var()`: Returns the variance of the Series.
21. `sum()`: Returns the sum of all elements in the Series.
22. `mode()`: Returns the mode (most frequent) value in the Series.
23. `idxmin()`: Returns the index of the minimum value.
24. `idxmax()`: Returns the index of the maximum value.
25. `apply(func)`: Applies a function to each element in the Series.
26. `map(dict_or_func)`: Maps values in the Series to new values using a dictionary or function.
27. `value_counts()`: Returns a Series containing counts of unique values.
28. `astype(dtype)`: Converts the data type of the Series.
29. `sort_values()`: Sorts the Series by values.
30. `sort_index()`: Sorts the Series by index labels.
31. `isna()` or `isnull()`: Returns a Boolean Series indicating missing values.
32. `notna()` or `notnull()`: Returns a Boolean Series indicating non-missing values.
33. `str`: Accesses string methods for Series with string data type.

### Head and Tail

The `.head` and `.tail` methods are useful for pulling out values at the start or end of the series,
respectively. These methods are used to quickly inspect a chunk of the data.

### Indexing 


Let’s shift the focus onto pulling data out by using indexing operators. You can index directly on
a series object, but this is not recommended. Use the `.iloc` or `loc` to index.


The `.loc` attribute deals with index labels. It allows you to pull out pieces of the series. You can
pass in the following into an index operation on .loc:
- A scalar value of one of the index labels
- A list of index labels.
- A slice of labels (closed interval so it includes the stop value).
- An index.
- A boolean array (same index labels as the series, but with True or False values.
- A function that accepts a series and returns one of the above.

> If we want to return a series object, we can index it with a list of positions. This can be a list
with a single index in it or multiple index values. The following code will return a series with the
first, second, and last values:

> We can also use slices with .iloc. In this case, slices behave as they do in Python lists and follow
the half-open interval. That is, they include the first index and go up to but do not include the last
index. If we want to return the first five items, we can use the .head method or the following code,
which takes index positions starting at 0 and includes 1, 2, 3, and 4, but does not include 5: